version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install -g @aws-amplify/cli
      - npm ci
      
  pre_build:
    commands:
      - echo "Setting up Amplify..."
      - amplify init --yes
      - amplify env checkout $CODEBUILD_WEBHOOK_HEAD_REF --yes
      
  build:
    commands:
      - echo "Building the app..."
      - amplify push --yes
      - npm run build
      
  post_build:
    commands:
      - echo "Deploying to Amplify..."
      - amplify publish --yes
      
artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: no 